### PR TITLE
Remove inaccurate Last Change

### PR DESCRIPTION
**Pull request by hokorobi**
"Last Change: " can not keep up with the update, so do not erase it?
I think that it is better to delete "Version:" as well.
How about transferring " syntax/plantuml.vim  TODO:" to Github Issues?

### CODE REVIEW

**Comment by aklt** [comment]
Hi, Thanks for the fixes!

Thanks for the fixes and good suggestions.  These headers needed an update!

Also, I think that there are very many strange plantuml keywords...

**Comment by hokorobi** [comment]
Thanks!

> Also, I think that there are very many strange plantuml keywords...
I will fix it when I notice it.

**Comment by aklt** [comment]
Sounds good.  Are you using plantuml a lot?

**Comment by hokorobi** [comment]
It depends on work.
Unfortunately, there seems to be no opportunity to use for a while.

**Pull request merged**
