### PR TITLE
Add padding keywrods at Version 8057

### PR DESCRIPTION
**Pull request by hokorobi**
http://plantuml.com/sequence-diagram#padding

### CODE REVIEW

**Comment by aklt** [comment]
Cool, thanks for this!

**Comment by hokorobi** [comment]
Thanks.

**Comment by aklt** [comment]
So are you back to using plantuml? ;-)

**Comment by hokorobi** [comment]
It is not used practically.
But, I am chasing the update of PlauntUML (:-)
Because I think there is something to be used during that time.

**Pull request merged**
