### PR TITLE
add first stab at indent file

### PR DESCRIPTION
**Pull request by scrooloose**
So far this only handles seq diagrams and state diagrams (as these are
what I have been using).

Should easily be extendable to other diagram types by adding to the
s:incIndent and s:decIndent vars.

### CODE REVIEW

**Comment by scrooloose** [comment]
@hokorobi I have added this indent file for sequence and state diagrams. I think you use other diagram types so, if you feel like it, you could add indent support for the diagrams you use :)

Also, I would appreciate some testing of my indent hacks to make sure I'm not an idiot :)

**Comment by hokorobi** [comment]
Great!
I didn't understand a way of making an indent setting file.
I'll try.

**Comment by scrooloose** [comment]
I had not written one before this either :)

The code is reasonably simple and I think now we should only need to update `s:incIndent` and `s:decIndent`. Whenever a line matches `s:incIndent`, the next line indent is increased, and the opposite for `s:decIndent`.

I think it should be easy to support other diagrams, but I am too lazy :-D

**Comment by aklt** [comment]
Great work you are doing guys, thanks a lot!

**Pull request merged**
