### PR TITLE
PlantUML colors can be 8 digits long do code transparency

### PR DESCRIPTION
**Pull request by chrisaga**

### CODE REVIEW

**Review by aklt — APPROVED** [review]

**Comment by aklt** [comment]
Cool, thanks for the contribution!

I wonder if it would be better to accept 6 or 8 characters and not 7, which this currently does.

What do you think?

**Comment by chrisaga** [comment]
> I wonder if it would be better to accept 6 or 8 characters and not 7, which this currently does.
Good question. I Confess it came to my mind but I didn't spend too much time ont it as accepting 7 characters was quite "safe".

I just tested it. PlanUML accepts 7 characters but it produces white whatever those digits are.
It's probably a minor bug. So should the syntax highlighting be more strict than the actual interpreter ?
I would say yes here since I cannot see why someone would write on purpose a color with 7 characters.

**Comment by aklt** [comment]
Yes, I agree, I think that only a 6 or an 8 character color should be legal.

**Comment by aklt** [comment]
Super cool, thank you!

**Pull request merged**
