### PR TITLE
Improve matching of arrows

### PR DESCRIPTION
**Pull request by hokorobi**
I tried to improve the matching of arrows. Include #42, #43.
~~There are still some buggy things, so I will try to adjust a bit more.~~
~~https://github.com/aklt/plantuml-syntax-test/blob/master/reference_2-06-1.uml etc.~~

### CODE REVIEW

**Comment by aklt** [comment]
Thank you!  I am away, but will see if I can merge it when the weekend comes :)

**Comment by hokorobi** [comment]
Thank you.

**Comment by aklt** [comment]
Hello again!  Sorry for being quiet.  I will merge this :-)

**Comment by aklt** [comment]
Thanks for the patch!

**Pull request merged**
