### PR TITLE
Add command to preview in Google Chrome

### PR DESCRIPTION
**Pull request by januswel**
Thank you for your great works, @aklt !!

I wanna preview UML diagrams to write in Vim, so I made this PR.
Would you think to merge this?

Thanks again!!

### CODE REVIEW

**Comment by aklt** [comment]
Hello @januswel Thanks for your patch. 

I am not sure if this functionality should be a part of this plugin, which only tries to support syntax highlighting and indentation and I think opening the resulting diagram in a browser should be done in 
 vim config or a different script.

**Comment by rhysd** [comment]
In addition, this patch has following problems:

- only works on macOS
- command is globally added in ftplugin

**Comment by januswel** [comment]
@aklt 
Thanks for your detailed comments.
I agreed with your intent and the direction of this plugin.
Never mind about this because I made the suggestion casually.

**Comment by aklt** [comment]
Hi @januswel, great and thanks for following up on this ;)

**Pull request closed without merging**
