### PR TITLE
Improve string recognition

### LINKED ISSUE #79: Single quote in component name highlighting
I *think* this is a bug but I don't know enough about syntax files to be sure.

```uml
[Payer's Bank Module] <<Internal Container>> as module
```

The single quote is treated as start of the comment even though it's in the brackets, i.e. name of the component:

image

### PR DESCRIPTION
**Pull request by hokorobi**
Fix #79

### CODE REVIEW

**Comment by hokorobi** [comment]
There are still some glitches, but I think it's slightly better.
Example: https://github.com/aklt/plantuml-syntax-test/blob/master/uml/reference_10-11-1.uml

From:
from

To:
to

**Comment by hokorobi** [comment]
Improved
new

**Comment by aklt** [comment]
Thank you for this, I think this is much better!

**Comment by hokorobi** [comment]
Thank you!

**Pull request merged**
