### PR TITLE
Add some keywords used in <style>..</style> section

### PR DESCRIPTION
**Pull request by chrisaga**
see https://plantuml.com/fr/style-evolution
Most of the keywords usable in <style> section are identical to those from skinparam.
Some are new.

### CODE REVIEW

**Comment by aklt** [comment]
Nice, thank you!

I am happy for some new contributions and will have a closer look during this week ,
it would be nice to use this occasion to update this plugin and maybe also 
the examples from the manual here https://aklt.github.io/plantuml/

**Comment by chrisaga** [comment]
This plugin does quite a good job already.
The next level would be to avoid colorizing keywords when used in a text context (names, labels, notes ...). I guess it would need some refactoring of the region definitions.

**Comment by aklt** [comment]
Thank you

**Comment by aklt** [comment]
The examples on https://aklt.github.io/plantuml/ are actually generated by running vim with this plugin loaded. 
It is a good way to see examples and also find bugs in the syntax highlighting.

**Comment by chrisaga** [comment]
> The examples on https://aklt.github.io/plantuml/ are actually generated by running vim with this plugin loaded. It is a good way to see examples and also find bugs in the syntax highlighting.

That's right. I can see there are still a few things we can improve.
I am currently working on embedded stylesheets. Not finished yet but it's promising. You can see it there : [https://github.com/chrisaga/plantuml-syntax/tree/stylesheet](https://github.com/chrisaga/plantuml-syntax/tree/stylesheet).
Unfortunately there are few examples and we'll need to make our own.

**Pull request merged**
